### ISSUE TITLE
服务端闪退

### ISSUE THREAD

**Issue by Kanbe-Kotori** [Paindar/AcademyMonster#27]
个人怀疑是NetworkManager类的sendArcGenTo()方法没有标@SideOnly的@Annotation。
完整bug-report如下：
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BedPatch (bedpatch-2.2-1.12.2.jar)
  CorePlugin (AcademyCraft-1.1.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 20-4-27 下午6:24
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at cn.paindar.academymonster.network.NetworkManager.sendArcGenTo(NetworkManager.java:144)
	at cn.paindar.academymonster.ability.AMArcGen.start(AMArcGen.java:79)
	at cn.paindar.academymonster.entity.ai.EntityAIRange.execute(EntityAIRange.java:52)
	at cn.paindar.academymonster.entity.datapart.MobSkillData.tick(MobSkillData.java:68)
	at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224)
	at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:235)
	at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32)
	at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:251)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:565)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2420)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:331)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:51)
	at net.minecraft.world.World.func_72866_a(World.java:2317)
	at net.minecraft.world.World.func_72870_g(World.java:2271)
	at net.minecraft.world.World.func_72939_s(World.java:2037)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@745ada9a from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 26 more
Caused by: java.lang.RuntimeException: Attempted to load class bsb for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cn.paindar.academymonster.network.NetworkManager.sendArcGenTo(NetworkManager.java:144)
	at cn.paindar.academymonster.ability.AMArcGen.start(AMArcGen.java:79)
	at cn.paindar.academymonster.entity.ai.EntityAIRange.execute(EntityAIRange.java:52)
	at cn.paindar.academymonster.entity.datapart.MobSkillData.tick(MobSkillData.java:68)
	at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224)
	at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:235)
	at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32)
	at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:251)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:565)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2420)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:331)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:51)
	at net.minecraft.world.World.func_72866_a(World.java:2317)
	at net.minecraft.world.World.func_72870_g(World.java:2271)

-- Entity being ticked --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.entity.monster.EntitySkeleton)
	Entity ID: 38
	Entity Name: Skeleton
	Entity's Exact location: 131.71, 67.00, 240.50
	Entity's Block location: World: (131,67,240), Chunk: (at 3,4,0 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2037)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['woshisb'/84, l='world', x=128.49, y=67.00, z=240.66](woshisb at 128.4903560435972,67.0,240.66098045536285)]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 2753625753331726959
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (104,64,248), Chunk: (at 8,4,8 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 28237 game time, 28237 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 31513 (now: false), thunder time: 97726 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 714697152 bytes (681 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	CraftBukkit Information: 
   Running: CatServer version git-CatServer-1.12.2-145a50c (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING Craft Async Scheduler Management Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Thread-11: [java.lang.Thread.sleep(Native Method), cn.academy.analytic.DelaySender.run(AnalyticDataListener.java:230)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], RUNNABLE Thread-4: [java.io.FileOutputStream.writeBytes(Native Method), java.io.FileOutputStream.write(Unknown Source), java.io.BufferedOutputStream.flushBuffer(Unknown Source), java.io.BufferedOutputStream.write(Unknown Source), java.io.PrintStream.write(Unknown Source), java.io.PrintStream.write(Unknown Source), org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82), java.io.FilterOutputStream.write(Unknown Source), java.io.PrintStream.write(Unknown Source), java.io.FilterOutputStream.write(Unknown Source), org.bukkit.craftbukkit.v1_12_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:40), java.lang.Thread.run(Unknown Source)], RUNNABLE DestroyJavaVM: [], RUNNABLE Netty Server IO #3: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], TIMED_WAITING threadDeathWatcher-2-1: [java.lang.Thread.sleep(Native Method), io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152), io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE Netty Server IO #2: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:99)], RUNNABLE Netty Server IO #1: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source), sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Unknown Source)], RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method), org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761), org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794), org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214), jline.WindowsTerminal.access$000(WindowsTerminal.java:54), jline.WindowsTerminal$1.read(WindowsTerminal.java:156), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243), jline.internal.InputStreamReader.read(InputStreamReader.java:257), jline.internal.InputStreamReader.read(InputStreamReader.java:194), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126), jline.console.ConsoleReader.readBinding(ConsoleReader.java:2211), jline.console.ConsoleReader.readLine(ConsoleReader.java:2460), jline.console.ConsoleReader.readLine(ConsoleReader.java:2372), net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:120)], RUNNABLE Signal Dispatcher: [], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Unknown Source), java.lang.ref.Reference.tryHandlePending(Unknown Source), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:92)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:29), net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120), net.minecraft.crash.CrashReport.<init>(CrashReport.java:41), net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:361), net.minecraft.world.World.func_72939_s(World.java:2043), net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:756), net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905), net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472), net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629), java.lang.Thread.run(Unknown Source)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275), java.lang.Thread.run(Unknown Source)], RUNNABLE Attach Listener: [], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:44), net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Timer-1: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)],}
   
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version        | Source                          | Signature                                |
	|:------ |:-------------- |:-------------- |:------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2         | minecraft.jar                   | None                                     |
	| LCHIJA | mcp            | 9.42           | minecraft.jar                   | None                                     |
	| LCHIJA | FML            | 8.0.99.99      | CatServer-145a50c-universal.jar | None                                     |
	| LCHIJA | forge          | 14.23.5.2854   | CatServer-145a50c-universal.jar | None                                     |
	| LCHIJA | LambdaLib|Core | 0.1.9          | minecraft.jar                   | None                                     |
	| LCHIJA | smoothfontcore | mc1.12.2-2.1.1 | minecraft.jar                   | None                                     |
	| LCHIJA | foamfixcore    | 7.7.4          | minecraft.jar                   | None                                     |
	| LCHIJA | lambdalib2     | 0.1.9          | AcademyCraft-1.1.2.jar          | None                                     |
	| LCHIJA | academy        | 1.1.2          | AcademyCraft-1.1.2.jar          | None                                     |
	| LCHIJA | academymonster | 1.1.0a         | AcademyMonster-1.1.0a.jar       | None                                     |
	| LCHIJA | applecore      | 3.2.0          | AppleCore-mc1.12.2-3.2.0.jar    | None                                     |
	| LCHIJA | jei            | 4.15.0.293     | jei_1.12.2-4.15.0.293.jar       | None                                     |
	| LCHIJA | appleskin      | 1.0.9          | AppleSkin-mc1.12-1.0.9.jar      | None                                     |
	| LCHIJA | bedpatch       | 2.2            | bedpatch-2.2-1.12.2.jar         | 6bf7527e690fb5e8719b9832bce5000a3e87dfe6 |
	| LCHIJA | fastleafdecay  | v14            | FastLeafDecay-v14.jar           | None                                     |
	| LCHIJA | foamfix        | 0.10.10-1.12.2 | foamfix-0.10.10-1.12.2.jar      | None                                     |
	| LCHIJA | gravestone     | 1.10.3         | gravestone-1.10.3.jar           | None                                     |
	| LCHIJA | waila          | 1.8.26         | Hwyla-1.8.26-B41_1.12.2.jar     | None                                     |
	| LCHIJA | journeymap     | 1.12.2-5.7.1   | journeymap-1.12.2-5.7.1.jar     | None                                     |

	Loaded coremods (and transformers): 
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
CorePlugin (AcademyCraft-1.1.2.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
  bre.smoothfont.asm.Transformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['woshisb'/84, l='world', x=128.49, y=67.00, z=240.66](woshisb at 128.4903560435972,67.0,240.66098045536285)]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Kanbe-Kotori** [comment]
我好像交错项目了
