### ISSUE TITLE
服务端，遇到超能力怪就崩端

### ISSUE THREAD

**Issue by vcup** [Paindar/AcademyMonster#30]
rt，我看到#27 遇到了和我一样的问题，连日志动一样一样的，我不知道为什么最后他关闭了那条问题
这个模组还是很有意思的，我想跟我的小伙伴们一起在世界里被超能力怪抄家，希望能早些解决
错误报告如下
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.2-core.jar)
  SurgeLoadingPlugin ([潮涌]Surge-1.12.2-2.0.77.jar)
  MovingWorldCore ([达芬奇的船前置]movingworld-1.12-6.353-full.jar)
  CorePlugin ([学园都市]AcademyCraft-1.1.3.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([泡沫修复]foamfix-0.10.11-1.12.2.jar)
  OpenModsCorePlugin ([开放式方块前置]OpenModsLib-1.12.2-0.12.2.jar)
  Quark Plugin ([夸克]Quark-r1.6-178.jar)
  PhosphorFMLLoadingPlugin ([磷]phosphor-1.12.2-0.2.6+build50-universal.jar)
  TransformLoader ([动态环境]DynamicSurroundings-1.12.2-3.6.1.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 21-1-1 下午1:03
Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at cn.paindar.academymonster.network.NetworkManager.sendArcGenTo(NetworkManager.java:144)
	at cn.paindar.academymonster.ability.AMArcGen.start(AMArcGen.java:79)
	at cn.paindar.academymonster.entity.ai.EntityAIRange.execute(EntityAIRange.java:52)
	at cn.paindar.academymonster.entity.datapart.MobSkillData.tick(MobSkillData.java:68)
	at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224)
	at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:247)
	at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32)
	at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:264)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_533_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@77d18d0b from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 27 more
Caused by: java.lang.RuntimeException: Attempted to load class bsb for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 29 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cn.paindar.academymonster.network.NetworkManager.sendArcGenTo(NetworkManager.java:144)
	at cn.paindar.academymonster.ability.AMArcGen.start(AMArcGen.java:79)
	at cn.paindar.academymonster.entity.ai.EntityAIRange.execute(EntityAIRange.java:52)
	at cn.paindar.academymonster.entity.datapart.MobSkillData.tick(MobSkillData.java:68)
	at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224)
	at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:247)
	at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32)
	at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:264)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_533_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
	Entity ID: 159
	Entity Name: ǝᴉqɯoZ
	Entity's Exact location: 140.52, 118.92, 306.52
	Entity's Block location: World: (140,118,306), Chunk: (at 12,7,2 in 8,19; contains blocks 128,0,304 to 143,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.06, -0.16, -0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['vcup'/1740, l='world', x=140.01, y=118.00, z=305.75]]
	Chunk stats: ServerChunkCache: 1681 Drop: 0
	Level seed: -5431489913915834007
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (36,64,240), Chunk: (at 4,4,0 in 2,15; contains blocks 32,0,240 to 47,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 139759 game time, 139759 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 15751 (now: true), thunder time: 4860 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1075958408 bytes (1026 MB) / 2011168768 bytes (1918 MB) up to 2011168768 bytes (1918 MB)
	JVM Flags: 2 total; -Xms1G -Xms2G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                 | Source                                              | Signature                                |
	|:------ |:-------------------------------------------- |:----------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                  | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                                          | 9.42                    | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99               | forge-1.12.2.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2855            | forge-1.12.2.jar                                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | LambdaLib|Core                               | 0.2.0                   | minecraft.jar                                       | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                         | minecraft.jar                                       | None                                     |
	| LCHIJA | openmodscore                                 | 0.12.2                  | minecraft.jar                                       | None                                     |
	| LCHIJA | foamfixcore                                  | 7.7.4                   | minecraft.jar                                       | None                                     |
	| LCHIJA | aiimprovements                               | 0.0.1.3                 | [AI改进]AIImprovements-1.12-0.0.1b3.jar               | None                                     |
	| LCHIJA | ic2                                          | 2.8.170-ex112           | [IC2]industrialcraft-2-2.8.170-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jei                                          | 4.16.1.301              | [JEI]jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCHIJA | coroutil                                     | 1.12.1-1.2.37           | [僵尸意识前置]coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | zombieawareness                              | 1.12.1-1.11.16          | [僵尸意识]ZombieAwareness-1.12.1-1.11.16.jar            | None                                     |
	| LCHIJA | extendedrenderer                             | v1.0                    | [僵尸意识前置]coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | configmod                                    | v1.0                    | [僵尸意识前置]coroutil-1.12.1-1.2.37.jar                  | None                                     |
	| LCHIJA | orelib                                       | 3.6.0.1                 | [动态环境前置]OreLib-1.12.2-3.6.0.1.jar                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                                    | 3.6.1.0                 | [动态环境]DynamicSurroundings-1.12.2-3.6.1.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | mantle                                       | 1.12-1.3.3.55           | [匠魂2前置]Mantle-1.12-1.3.3.55.jar                     | None                                     |
	| LCHIJA | tombstone                                    | 3.7.4                   | [墓碑]tombstone-3.7.4-1.12.2.jar                      | None                                     |
	| LCHIJA | quark                                        | r1.6-178                | [夸克]Quark-r1.6-178.jar                              | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                   | [神秘时代前置]Baubles-1.12-1.5.2.jar                      | None                                     |
	| LCHIJA | thaumcraft                                   | 6.1.BETA26              | [神秘时代]Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | twilightforest                               | 3.11.1021               | [暮色森林]twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.13.0.183       | [匠魂2]TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCHIJA | lostcities                                   | 2.0.22                  | [失落的城市]lostcities-1.12-2.0.22.jar                   | None                                     |
	| LCHIJA | lostsouls                                    | 1.1.4                   | [失落的灵魂]lostsouls-1.12-1.1.4.jar                     | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-32                  | [夸克前置]AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | harvestcraft                                 | 1.12.2zb                | [潘马斯农场]Pam's+HarvestCraft+1.12.2zg.jar              | None                                     |
	| LCHIJA | mm_lib                                       | 2.1.0                   | [妖怪之山通用库(樱前置)]MMLib-2.1.0.jar                       | None                                     |
	| LCHIJA | lambdalib2                                   | 0.2.0                   | [学园都市]AcademyCraft-1.1.3.jar                        | None                                     |
	| LCHIJA | academy                                      | 1.1.3                   | [学园都市]AcademyCraft-1.1.3.jar                        | None                                     |
	| LCHIJA | patchouli                                    | 1.0-20                  | [帕秋莉手册]Patchouli-1.0-20.jar                         | None                                     |
	| LCHIJA | openmods                                     | 0.12.2                  | [开放式方块前置]OpenModsLib-1.12.2-0.12.2.jar              | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks                                   | 1.8.1                   | [开放式方块]OpenBlocks-1.12.2-1.8.1.jar                  | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | cyclicmagic                                  | 1.19.16                 | [循环]Cyclic-1.12.2-1.19.16.jar                       | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCHIJA | mobrebirth                                   | 7.0.6                   | [怪物重生]MobRebirth-1.12.2-7.0.6.jar                   | None                                     |
	| LCHIJA | battletowers                                 | 1.6.5                   | [战斗高塔]BattleTowers-1.12.2.jar                       | None                                     |
	| LCHIJA | gokistats                                    | 1.2.8.3                 | [技能树]gokiStats-1.2.8.3.jar                          | None                                     |
	| LCHIJA | flammpfeil.slashblade                        | mc1.12-r33              | [拔刀剑]SlashBlade-mc1.12-r33.jar                      | None                                     |
	| LCHIJA | sakura                                       | 1.0.4.1-1.12.2          | [樱花]Sakura-1.0.4.1-1.12.2.jar                       | None                                     |
	| LCHIJA | slashblade_addon                             | 1.6.0                   | [拔刀剑附属-拔刀剑日系附属包]SJAP-1.6.0.jar                      | None                                     |
	| LCHIJA | lastsmith                                    | 2.1.3-1.12.2            | [拔刀剑附属-最后的太刀匠人]TLS-2.1.3-1.12.2.jar                 | None                                     |
	| LCHIJA | travelersbackpack                            | 1.0.35                  | [旅行者背包]TravelersBackpack-1.12.2-1.0.35.jar          | None                                     |
	| LCHIJA | ironchest                                    | 1.12.2-7.0.67.844       | [更多箱子]ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | serverlocalization                           | 1.0                     | [服务器本地化]serverlocalization-1.0.1.jar                | None                                     |
	| LCHIJA | fastleafdecay                                | v14                     | [树叶快速腐烂]FastLeafDecay-v14.jar                       | None                                     |
	| LCHIJA | dimdoors                                     | 1.12.2-3.1.2+UNOFFICIAL | [次元门]DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar   | None                                     |
	| LCHIJA | foamfix                                      | 0.10.11-1.12.2          | [泡沫修复]foamfix-0.10.11-1.12.2.jar                    | None                                     |
	| LCHIJA | surge                                        | 2.0.77                  | [潮涌]Surge-1.12.2-2.0.77.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | grimoireofgaia                               | 1.7.2                   | [盖亚魔典]GrimoireOfGaia3-1.12.2-1.7.2.jar              | None                                     |
	| LCHIJA | infernalmobs                                 | 1.7.6                   | [精英怪]InfernalMobs-1.12.2.jar                        | None                                     |
	| LCHIJA | autoplant                                    | 1.12-1.0.0              | [自动种植植物]autoplant-1.12-1.0.0.jar                    | None                                     |
	| LCHIJA | aoa3                                         | 3.3.6                   | [虚无世界3]AoA3-3.3.6.jar                               | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJA | academymonster                               | 1.1.0a                  | [超能力怪物]AcademyMonster-1.1.0a.jar                    | None                                     |
	| LCHIJA | touhou_little_maid                           | 1.2.3                   | [车万女仆]touhoulittlemaid-1.12.2-1.2.3-release.jar     | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.353              | [达芬奇的船前置]movingworld-1.12-6.353-full.jar            | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@           | [达芬奇的船]davincisvessels-1.12-6.355-full.jar          | None                                     |
	| LCHIJA | veinminer                                    | 0.38.2                  | [连锁挖矿]VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCHIJA | veinminermodsupport                          | 0.38.2                  | [连锁挖矿]VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCHIJA | thebetweenlands                              | 3.7.2                   | [交错次元]TheBetweenlands-3.7.2-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | phosphor-lighting                            | 1.12.2-0.2.6            | [磷]phosphor-1.12.2-0.2.6+build50-universal.jar      | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.2-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
SurgeLoadingPlugin ([潮涌]Surge-1.12.2-2.0.77.jar)
  
MovingWorldCore ([达芬奇的船前置]movingworld-1.12-6.353-full.jar)
  
CorePlugin ([学园都市]AcademyCraft-1.1.3.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([泡沫修复]foamfix-0.10.11-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
OpenModsCorePlugin ([开放式方块前置]OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Quark Plugin ([夸克]Quark-r1.6-178.jar)
  vazkii.quark.base.asm.ClassTransformer
PhosphorFMLLoadingPlugin ([磷]phosphor-1.12.2-0.2.6+build50-universal.jar)
  
TransformLoader ([动态环境]DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- quarkIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['vcup'/1740, l='world', x=140.01, y=118.00, z=305.75]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)```

**Comment by vcup** [comment]
看上去就是一只名字倒过来写的鬼人正邪(: )拿到了超能力，然后gank了服务器( ǝᴉqɯoZ这种名字是怎么打出来的

**Comment by Paindar** [comment]
我不太确定问题出在哪儿——至少从模组代码上看不出什么问题。
我只能猜测是某个（或是某些MOD）和AM产生了冲突。
实际上我已经很久没有碰过有关于MC的东西了。
我能给你的建议只有通过逐步减少MOD来确定究竟是哪个（或者哪些MOD）和AM产生了冲突。
祝你游戏愉快！
