### ISSUE TITLE
关于#30 的后续

### ISSUE THREAD

**Issue by vcup** [Paindar/AcademyMonster#31]
作者在#30 这个问题中回复说，服务端崩端可能是模组冲突。(至于为什么我新开了个issues而不是再打开原来的那个issues，因为我甚至不知道可以重新打开问题)
我试着把除超能力怪物和学园都市以外的模组删除之后，再进去游戏，依旧崩端。
崩溃之前我看到一个僵尸使用了电子光束，然后就崩了
以下是完整的崩溃报告
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin ([学园都市]AcademyCraft-1.1.3.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 21-1-2 下午3:31
Description: Ticking entity

java.lang.NoClassDefFoundError: cn/paindar/academymonster/entity/EntityMobMDRay
	at cn.paindar.academymonster.network.NetworkManager.sendMdRayEffectTo(NetworkManager.java:110)
	at cn.paindar.academymonster.ability.AMElectronBomb.lambda$start$0(AMElectronBomb.java:55)
	at cn.lambdalib2.util.entityx.EntityX.update(EntityX.java:65)
	at cn.lambdalib2.util.entityx.EntityAdvanced.func_70071_h_(EntityAdvanced.java:31)
	at cn.paindar.academymonster.entity.EntityMobMdBall.func_70071_h_(EntityMobMdBall.java:127)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: cn.paindar.academymonster.entity.EntityMobMDRay
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4dd94a58 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 17 more
Caused by: java.lang.RuntimeException: Attempted to load class cn/paindar/academymonster/entity/EntityMobMDRay for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at cn.paindar.academymonster.network.NetworkManager.sendMdRayEffectTo(NetworkManager.java:110)
	at cn.paindar.academymonster.ability.AMElectronBomb.lambda$start$0(AMElectronBomb.java:55)
	at cn.lambdalib2.util.entityx.EntityX.update(EntityX.java:65)
	at cn.lambdalib2.util.entityx.EntityAdvanced.func_70071_h_(EntityAdvanced.java:31)
	at cn.paindar.academymonster.entity.EntityMobMdBall.func_70071_h_(EntityMobMdBall.java:127)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: academymonster:entitymobmdball (cn.paindar.academymonster.entity.EntityMobMdBall)
	Entity ID: 2581
	Entity Name: entity.EntityMobMdBall.name
	Entity's Exact location: -445.01, 67.31, 256.82
	Entity's Block location: World: (-446,67,256), Chunk: (at 2,4,0 in -28,16; contains blocks -448,0,256 to -433,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['vcup'/253, l='world', x=-448.65, y=68.00, z=256.27]]
	Chunk stats: ServerChunkCache: 1691 Drop: 0
	Level seed: -3100858002386431576
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-248,64,252), Chunk: (at 8,4,12 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 79805 game time, 13684 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 36157 (now: false), thunder time: 10976 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1252151088 bytes (1194 MB) / 1578631168 bytes (1505 MB) up to 2382364672 bytes (2272 MB)
	JVM Flags: 2 total; -Xms1G -Xmx2556M
	IntCache: cache: 2, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                           | Signature                                |
	|:------ |:-------------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                    | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                    | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2855 | forge-1.12.2.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | LambdaLib|Core | 0.2.0        | minecraft.jar                    | None                                     |
	| LCHIJA | lambdalib2     | 0.2.0        | [学园都市]AcademyCraft-1.1.3.jar     | None                                     |
	| LCHIJA | academy        | 1.1.3        | [学园都市]AcademyCraft-1.1.3.jar     | None                                     |
	| LCHIJA | academymonster | 1.1.0a       | [超能力怪物]AcademyMonster-1.1.0a.jar | None                                     |

	Loaded coremods (and transformers): 
CorePlugin ([学园都市]AcademyCraft-1.1.3.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['vcup'/253, l='world', x=-448.65, y=68.00, z=256.27]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)```

**Comment by Paindar** [comment]
已经确认到BUG了，目前的情况是在新版本修复以前可能不太能在联机环境玩上AM。
等我找个时间修一下吧

**Comment by Paindar** [comment]
突然想起来一件事，如果不出意外的话配置文件里可以禁用掉某些技能以使怪物无法使用，但是这无法对已经获取某些技能的怪物生效。
因此在配置文件里设置完并重启服务器后你可能需要手动清除一下地图上的敌对生物，也就是在控制台手动将难度调成和平后再调回去

**Comment by 10086mea** [comment]
哈哈哈哈哈哈哈我也遇到了同样的问题，换端删地图等操作都无法解决，从mcbbs一直扒到github，总算找到相关讨论贴了

**Comment by vcup** [comment]
> 

这么搞人的模组还有别人拿来联机也是挺神奇的哈哈哈

**Comment by vcup** [comment]
> 哈哈哈哈哈哈哈我也遇到了同样的问题，换端删地图等操作都无法解决，从mcbbs一直扒到github，总算找到相关讨论贴了

这么搞人的模组还有别人拿来联机也是挺神奇的哈哈哈

**Comment by 10086mea** [comment]
秒回惊了，这模组我感觉可玩性挺高的，再给怪物加上超能力就是个难度适中娱乐性蛮高的科技生存，可惜怪物附属一直崩给我气得不轻，我看看能不能曲线救国挽救一下

**Comment by vcup** [comment]
> 秒回惊了，这模组我感觉可玩性挺高的，再给怪物加上超能力就是个难度适中娱乐性蛮高的科技生存，可惜怪物附属一直崩给我气得不轻，我看看能不能曲线救国挽救一下

正好看到邮件，这个问题的话好像只能禁用超能力了，进去之后怪物可能还有超能力就后台杀掉吧，反正当时我组出来这么个服务端却因为难度太高没人愿意陪我玩了。因为我加了其他高难模组(小声

**Comment by vcup** [comment]
> 秒回惊了，这模组我感觉可玩性挺高的，再给怪物加上超能力就是个难度适中娱乐性蛮高的科技生存，可惜怪物附属一直崩给我气得不轻，我看看能不能曲线救国挽救一下

话说你这id，老dd了(字面)，我很久没关注过，不知道还有没有在活动了

**Comment by 10086mea** [comment]
我为了吐槽一句特意注册了个账号，不让用中文名我就随手把这个旧id填上了，居然一眼就看出成分，猛啊
有没有推荐的类似的怪物增强模组啊？不加怪物增强可玩性太差了

**Comment by Paindar** [comment]
AC我不知道，因为我已经退出LI了。
AM的话发新版本是个很困难的事情，因为我魔改了一个AC版本，自己再往里面添加一些内容，包括药物和AC装甲这些。我后续的AM的更新也是基于这个魔改AC的版本的。
然后比较倒霉的地方就在这里了，这个基于魔改的版本在官方AC版本上跑不动。
最早我是另外维护了一个能适配官方版本的AM，但是后来我逐渐没时间了（要社畜的），加上对于MC我个人是没什么热情和动力了，所以AM虽然一直有做个稳定版本的想法但一直没实现。

**Comment by 10086mea** [comment]
我现在打开了移除报错实体的设置，已经可以顶着后台一片红玩了，实际体验起来除了部分怪物会在释放技能瞬间被移除之外没什么异样，玩得很开心，谢谢大佬为MC社区的贡献
